<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260130185817 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agreement (id INT AUTO_INCREMENT NOT NULL, payer_id INT DEFAULT NULL, requesting_company_id INT DEFAULT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, agreement_type VARCHAR(100) DEFAULT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, payment_term_days INT DEFAULT NULL, terms LONGTEXT DEFAULT NULL, covered_services LONGTEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, auto_renew TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_2E655A24C17AD9A9 (payer_id), INDEX IDX_2E655A24E3FB3114 (requesting_company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE appointment (id INT AUTO_INCREMENT NOT NULL, schedule_id INT NOT NULL, professional_id INT NOT NULL, consultation_type_id INT DEFAULT NULL, payer_id INT DEFAULT NULL, authorization_id INT DEFAULT NULL, cancellation_type_id INT DEFAULT NULL, appointment_number VARCHAR(50) NOT NULL, patient_name VARCHAR(100) NOT NULL, patient_rut VARCHAR(20) NOT NULL, patient_email VARCHAR(100) DEFAULT NULL, patient_phone VARCHAR(50) DEFAULT NULL, appointment_date_time DATETIME NOT NULL, duration_minutes INT DEFAULT 30 NOT NULL, status VARCHAR(50) NOT NULL, cancellation_date DATETIME DEFAULT NULL, cancellation_reason LONGTEXT DEFAULT NULL, reason LONGTEXT DEFAULT NULL, observations LONGTEXT DEFAULT NULL, is_first_time TINYINT(1) DEFAULT 0 NOT NULL, reminder_sent TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_FE38F844D1CEA01A (appointment_number), INDEX IDX_FE38F844A40BC2D5 (schedule_id), INDEX IDX_FE38F844DB77003 (professional_id), INDEX IDX_FE38F844804F7D71 (consultation_type_id), INDEX IDX_FE38F844C17AD9A9 (payer_id), INDEX IDX_FE38F8442F8B0EB2 (authorization_id), INDEX IDX_FE38F844B0AFEE5E (cancellation_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_package (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, description LONGTEXT DEFAULT NULL, package_type VARCHAR(100) DEFAULT NULL, package_price NUMERIC(10, 2) DEFAULT NULL, is_pre_assembled TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE authorization (id INT AUTO_INCREMENT NOT NULL, payer_id INT NOT NULL, service_type_id INT DEFAULT NULL, authorization_code VARCHAR(50) NOT NULL, patient_name VARCHAR(100) DEFAULT NULL, patient_rut VARCHAR(20) DEFAULT NULL, authorization_date DATE NOT NULL, expiration_date DATE DEFAULT NULL, authorized_services LONGTEXT DEFAULT NULL, authorized_amount NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(50) NOT NULL, observations LONGTEXT DEFAULT NULL, authorized_by VARCHAR(100) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_7A6D8BEFC17AD9A9 (payer_id), INDEX IDX_7A6D8BEFAC8DE0F (service_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bed (id INT AUTO_INCREMENT NOT NULL, bed_type_id INT NOT NULL, room_id INT DEFAULT NULL, bed_number VARCHAR(20) NOT NULL, floor VARCHAR(50) DEFAULT NULL, wing VARCHAR(100) DEFAULT NULL, status VARCHAR(50) NOT NULL, last_maintenance_date DATE DEFAULT NULL, observations LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E647FCFF8158330E (bed_type_id), INDEX IDX_E647FCFF54177093 (room_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bed_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, daily_rate NUMERIC(10, 2) DEFAULT NULL, requires_special_care TINYINT(1) DEFAULT 0 NOT NULL, capacity INT DEFAULT 1 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blocking_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, color VARCHAR(30) DEFAULT NULL, requires_approval TINYINT(1) DEFAULT 0 NOT NULL, allows_override TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE branch (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(100) DEFAULT NULL, address LONGTEXT DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, region VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE branch_payer (id INT AUTO_INCREMENT NOT NULL, branch_id INT NOT NULL, payer_id INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_2F7A59CEDCD6CC49 (branch_id), INDEX IDX_2F7A59CEC17AD9A9 (payer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE branch_service_type (id INT AUTO_INCREMENT NOT NULL, branch_id INT NOT NULL, service_type_id INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_1F793463DCD6CC49 (branch_id), INDEX IDX_1F793463AC8DE0F (service_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE budget_item (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, description LONGTEXT DEFAULT NULL, unit_price NUMERIC(10, 2) DEFAULT NULL, unit_of_measure VARCHAR(50) DEFAULT NULL, category VARCHAR(50) DEFAULT NULL, is_taxable TINYINT(1) DEFAULT 0 NOT NULL, requires_authorization TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `business_activity` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cancellation_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, requires_justification TINYINT(1) DEFAULT 0 NOT NULL, allows_refund TINYINT(1) DEFAULT 0 NOT NULL, affects_statistics TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clinic (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(50) DEFAULT NULL, rut VARCHAR(20) DEFAULT NULL, address LONGTEXT NOT NULL, city VARCHAR(100) DEFAULT NULL, region VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, director VARCHAR(100) DEFAULT NULL, total_beds INT DEFAULT NULL, has_emergency TINYINT(1) DEFAULT 0 NOT NULL, has_icu TINYINT(1) DEFAULT 0 NOT NULL, is_main_facility TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE consultation_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, default_duration_minutes INT DEFAULT NULL, requires_prior_appointment TINYINT(1) DEFAULT 0 NOT NULL, is_emergency TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cost_center (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(100) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, demonym VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE department (id INT AUTO_INCREMENT NOT NULL, branch_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(100) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_CD1DE18ADCD6CC49 (branch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `education_level` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value TINYINT(1) DEFAULT 1 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE eno_pathology (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(200) NOT NULL, description LONGTEXT DEFAULT NULL, icd10_code VARCHAR(20) DEFAULT NULL, requires_specialist TINYINT(1) DEFAULT 0 NOT NULL, is_chronic TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `ethnic_group` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exam_package (id INT AUTO_INCREMENT NOT NULL, medical_service_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, is_billable TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D3CE3EFDC61D802A (medical_service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exam_package_detail (id INT AUTO_INCREMENT NOT NULL, exam_package_id INT NOT NULL, medical_service_id INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_8E28E519E644D1AA (exam_package_id), INDEX IDX_8E28E519C61D802A (medical_service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE external_referrer (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(50) DEFAULT NULL, referrer_type VARCHAR(100) DEFAULT NULL, rut VARCHAR(20) DEFAULT NULL, address LONGTEXT DEFAULT NULL, contact_person VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, has_agreement TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE figure (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) NOT NULL, is_surgical_room TINYINT(1) NOT NULL, is_zero TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ges_pathology (id INT AUTO_INCREMENT NOT NULL, pathology_number VARCHAR(10) DEFAULT NULL, name VARCHAR(200) NOT NULL, description LONGTEXT DEFAULT NULL, min_age INT DEFAULT NULL, max_age INT DEFAULT NULL, min_age_months INT DEFAULT NULL, max_age_months INT DEFAULT NULL, gender_restriction VARCHAR(20) DEFAULT NULL, guaranteed_days INT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE group_permission (id INT AUTO_INCREMENT NOT NULL, group_id INT NOT NULL, created_by_id INT DEFAULT NULL, domain VARCHAR(100) NOT NULL, resource_id INT DEFAULT NULL, field_name VARCHAR(100) DEFAULT NULL, can_view TINYINT(1) NOT NULL, can_edit TINYINT(1) NOT NULL, can_delete TINYINT(1) NOT NULL, constraints JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_3784F318FE54D947 (group_id), INDEX IDX_3784F318B03A8386 (created_by_id), INDEX idx_group_permission_domain (domain), INDEX idx_group_permission_resource (domain, resource_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `health_insurance` (id INT AUTO_INCREMENT NOT NULL, health_insurance_type_id INT DEFAULT NULL, tax_affectation_type_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, interface_code VARCHAR(100) DEFAULT NULL, id_imed INT DEFAULT NULL, abbreviated_name VARCHAR(45) NOT NULL, is_default_value TINYINT(1) DEFAULT 1 NOT NULL, healthcare_prevition_hl7 VARCHAR(30) DEFAULT NULL, icon VARCHAR(45) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, INDEX IDX_558804DE54CCFBDD (health_insurance_type_id), INDEX IDX_558804DE588DA015 (tax_affectation_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE health_insurance_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value TINYINT(1) DEFAULT 1 NOT NULL, is_agreement TINYINT(1) DEFAULT 1 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `identification_type` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintainer_doctor_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintainer_education_level_detail (id INT AUTO_INCREMENT NOT NULL, education_level_id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D867A8A7D7A5352E (education_level_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintainer_insurance_administrator (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, rut VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintainer_job_position (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintainer_location (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description LONGTEXT DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, building VARCHAR(50) DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintainer_medical_box (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description LONGTEXT DEFAULT NULL, capacity INT DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, building VARCHAR(50) DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintainer_origin (id INT AUTO_INCREMENT NOT NULL, origin_type_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_23B5077C703B99FE (origin_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE maintainer_origin_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `marital_status` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value TINYINT(1) DEFAULT 1 NOT NULL, marital_status_code_hl7 VARCHAR(2) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medical_service (id INT AUTO_INCREMENT NOT NULL, figure_id INT DEFAULT NULL, budget_item_id INT DEFAULT NULL, service_type_id INT DEFAULT NULL, sub_company_id INT DEFAULT NULL, billing_sub_company_id INT DEFAULT NULL, code VARCHAR(20) NOT NULL, fonasa_code VARCHAR(20) DEFAULT NULL, name LONGTEXT NOT NULL, short_name VARCHAR(45) DEFAULT NULL, accounting_code_erp INT DEFAULT NULL, duration TIME DEFAULT NULL, description LONGTEXT DEFAULT NULL, applies_surcharge TINYINT(1) NOT NULL, is_imed TINYINT(1) NOT NULL, imed_code VARCHAR(20) DEFAULT NULL, interface_code VARCHAR(20) DEFAULT NULL, participation INT DEFAULT NULL, is_taxed TINYINT(1) NOT NULL, is_procedure TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_A79F7A1C5C011B5 (figure_id), INDEX IDX_A79F7A1CD0EC18BF (budget_item_id), INDEX IDX_A79F7A1CAC8DE0F (service_type_id), INDEX IDX_A79F7A1CBB50891B (sub_company_id), INDEX IDX_A79F7A1C3395B1AC (billing_sub_company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medical_service_bed_type (id INT AUTO_INCREMENT NOT NULL, medical_service_id INT NOT NULL, bed_type_id INT NOT NULL, quantity INT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_EEE3D850C61D802A (medical_service_id), INDEX IDX_EEE3D8508158330E (bed_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medical_service_budget_item (id INT AUTO_INCREMENT NOT NULL, medical_service_id INT NOT NULL, surgery_item_id INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_9E9803FBC61D802A (medical_service_id), INDEX IDX_9E9803FBA4665449 (surgery_item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medical_service_service (id INT AUTO_INCREMENT NOT NULL, medical_service_id INT NOT NULL, service_id INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D8EE37BEC61D802A (medical_service_id), INDEX IDX_D8EE37BEED5CA9E6 (service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `member` (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_group_membership (member_id INT NOT NULL, member_group_id INT NOT NULL, INDEX IDX_61D5C0D17597D3FE (member_id), INDEX IDX_61D5C0D19897AAD (member_group_id), PRIMARY KEY(member_id, member_group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE member_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, description VARCHAR(500) DEFAULT NULL, active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_FE1D13677153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE menu_items (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, route VARCHAR(255) DEFAULT NULL, icon VARCHAR(100) DEFAULT NULL, module VARCHAR(100) DEFAULT NULL, position INT NOT NULL, enabled TINYINT(1) NOT NULL, visible_in_sidebar TINYINT(1) NOT NULL, requires_auth TINYINT(1) NOT NULL, required_roles JSON DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_70B2CA2A727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `municipality` (id INT AUTO_INCREMENT NOT NULL, province_id INT NOT NULL, name VARCHAR(100) NOT NULL, municipality_code_hl7 VARCHAR(10) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, INDEX IDX_C6F56628E946114A (province_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `occupation` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value TINYINT(1) NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pathology_article (id INT AUTO_INCREMENT NOT NULL, ges_pathology_id INT NOT NULL, article_name VARCHAR(200) NOT NULL, article_code VARCHAR(20) DEFAULT NULL, description LONGTEXT DEFAULT NULL, quantity INT DEFAULT 1 NOT NULL, unit_of_measure VARCHAR(50) DEFAULT NULL, unit_cost NUMERIC(10, 2) DEFAULT NULL, is_mandatory TINYINT(1) DEFAULT 1 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B24A1BE1541D0E27 (ges_pathology_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payer (id INT AUTO_INCREMENT NOT NULL, payer_type_id INT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(150) NOT NULL, short_name VARCHAR(50) DEFAULT NULL, rut VARCHAR(20) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, address LONGTEXT DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, payment_days INT DEFAULT NULL, requires_authorization TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_41CB5B99BEA5E0F7 (payer_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payer_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, is_agreement TINYINT(1) DEFAULT 0 NOT NULL, is_default TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE permission (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, created_by_id INT DEFAULT NULL, domain VARCHAR(100) NOT NULL, resource_id INT DEFAULT NULL, field_name VARCHAR(100) DEFAULT NULL, can_view TINYINT(1) NOT NULL, can_edit TINYINT(1) NOT NULL, can_delete TINYINT(1) NOT NULL, constraints JSON DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_E04992AAA76ED395 (user_id), INDEX IDX_E04992AAB03A8386 (created_by_id), INDEX IDX_E04992AAA76ED395A7A91E0B (user_id, domain), INDEX IDX_E04992AAA7A91E0B89329D25 (domain, resource_id), UNIQUE INDEX unique_user_permission (user_id, domain, resource_id, field_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `person` (id INT AUTO_INCREMENT NOT NULL, identification_type_id INT DEFAULT NULL, education_level_id INT DEFAULT NULL, marital_status_id INT DEFAULT NULL, occupation_id INT DEFAULT NULL, ethnic_group_id INT DEFAULT NULL, religion_id INT DEFAULT NULL, gender_id INT DEFAULT NULL, nacionality_id INT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', identification VARCHAR(100) NOT NULL, name VARCHAR(60) NOT NULL, last_name VARCHAR(45) NOT NULL, middle_name VARCHAR(45) DEFAULT NULL, birth_date_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', death_date_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', non_medical_note LONGTEXT, photo_path VARCHAR(255) DEFAULT NULL, is_record_visibility TINYINT(1) DEFAULT 1 NOT NULL, record_viewed_date_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', social_name VARCHAR(50) DEFAULT NULL, number_of_children INT DEFAULT NULL, mobile_phone VARCHAR(20) NOT NULL, work_phone VARCHAR(20) DEFAULT NULL, home_phone VARCHAR(20) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, secondary_email VARCHAR(100) DEFAULT NULL, contact_method VARCHAR(50) DEFAULT NULL, twin_number INT DEFAULT NULL, INDEX IDX_34DCD176F54A83F (identification_type_id), INDEX IDX_34DCD176D7A5352E (education_level_id), INDEX IDX_34DCD176E559F9BF (marital_status_id), INDEX IDX_34DCD17622C8FC20 (occupation_id), INDEX IDX_34DCD176E7EEEDB3 (ethnic_group_id), INDEX IDX_34DCD176B7850CBD (religion_id), INDEX IDX_34DCD176708A0E0 (gender_id), INDEX IDX_34DCD1767949DE26 (nacionality_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_address (id INT AUTO_INCREMENT NOT NULL, id_person_id INT DEFAULT NULL, municipality_id INT DEFAULT NULL, country_id INT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', address VARCHAR(255) NOT NULL, street_number VARCHAR(10) NOT NULL, address_details VARCHAR(255) NOT NULL, INDEX IDX_2FD0DC08A14E0760 (id_person_id), INDEX IDX_2FD0DC08AE6F181C (municipality_id), INDEX IDX_2FD0DC08F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE professional (id INT AUTO_INCREMENT NOT NULL, specialty_id INT DEFAULT NULL, code VARCHAR(20) DEFAULT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, rut VARCHAR(20) NOT NULL, professional_type VARCHAR(50) DEFAULT NULL, license_number VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, mobile VARCHAR(50) DEFAULT NULL, address LONGTEXT DEFAULT NULL, hire_date DATE DEFAULT NULL, is_external TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B3B573AA9A353316 (specialty_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE professional_rate (id INT AUTO_INCREMENT NOT NULL, professional_id INT NOT NULL, service_id INT DEFAULT NULL, payer_id INT DEFAULT NULL, rate NUMERIC(10, 2) NOT NULL, effective_date DATE NOT NULL, expiration_date DATE DEFAULT NULL, observations LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_CDA906E7DB77003 (professional_id), INDEX IDX_CDA906E7ED5CA9E6 (service_id), INDEX IDX_CDA906E7C17AD9A9 (payer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `province` (id INT AUTO_INCREMENT NOT NULL, region_id INT NOT NULL, name VARCHAR(100) NOT NULL, province_code_hl7 VARCHAR(10) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, INDEX IDX_4ADAD40B98260155 (region_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `region` (id INT AUTO_INCREMENT NOT NULL, country_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, address_state_hl7 VARCHAR(10) DEFAULT NULL, region_code_hl7 VARCHAR(10) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, INDEX IDX_F62F176F92F3E70 (country_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `religion` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value TINYINT(1) DEFAULT 1 NOT NULL, religion_code_hl7 VARCHAR(10) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE requesting_company (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, business_name VARCHAR(150) NOT NULL, trade_name VARCHAR(50) DEFAULT NULL, rut VARCHAR(20) NOT NULL, address LONGTEXT DEFAULT NULL, contact_person VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, industry VARCHAR(100) DEFAULT NULL, number_of_employees INT DEFAULT NULL, discount_percentage NUMERIC(5, 2) DEFAULT NULL, payment_term_days INT DEFAULT NULL, has_agreement TINYINT(1) DEFAULT 0 NOT NULL, agreement_start_date DATE DEFAULT NULL, agreement_end_date DATE DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE room (id INT AUTO_INCREMENT NOT NULL, clinic_id INT DEFAULT NULL, room_number VARCHAR(50) NOT NULL, name VARCHAR(150) NOT NULL, room_type VARCHAR(100) DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, wing VARCHAR(100) DEFAULT NULL, capacity INT DEFAULT 1 NOT NULL, daily_rate NUMERIC(10, 2) DEFAULT NULL, status VARCHAR(50) NOT NULL, has_oxygen TINYINT(1) DEFAULT 0 NOT NULL, has_bathroom TINYINT(1) DEFAULT 0 NOT NULL, observations LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_729F519BCC22AD4 (clinic_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE schedule (id INT AUTO_INCREMENT NOT NULL, professional_id INT NOT NULL, consultation_type_id INT DEFAULT NULL, blocking_type_id INT DEFAULT NULL, schedule_date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL, slot_duration_minutes INT DEFAULT 30 NOT NULL, location VARCHAR(100) DEFAULT NULL, max_appointments INT DEFAULT 1 NOT NULL, is_blocked TINYINT(1) DEFAULT 0 NOT NULL, observations LONGTEXT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_5A3811FBDB77003 (professional_id), INDEX IDX_5A3811FB804F7D71 (consultation_type_id), INDEX IDX_5A3811FB6DB2886B (blocking_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, service_type_id INT DEFAULT NULL, specialty_id INT DEFAULT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(200) NOT NULL, description LONGTEXT DEFAULT NULL, base_price NUMERIC(10, 2) DEFAULT NULL, estimated_duration_minutes INT DEFAULT NULL, requires_authorization TINYINT(1) DEFAULT 0 NOT NULL, requires_specialist TINYINT(1) DEFAULT 0 NOT NULL, is_ambulatory TINYINT(1) DEFAULT 0 NOT NULL, fonasa_code VARCHAR(50) DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E19D9AD2AC8DE0F (service_type_id), INDEX IDX_E19D9AD29A353316 (specialty_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_package (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, is_billable TINYINT(1) NOT NULL, is_program TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_package_detail (id INT AUTO_INCREMENT NOT NULL, service_package_id INT NOT NULL, medical_service_id INT NOT NULL, quantity INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_139B51F9621D924B (service_package_id), INDEX IDX_139B51F9C61D802A (medical_service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, requires_authorization TINYINT(1) DEFAULT 0 NOT NULL, requires_bed_assignment TINYINT(1) DEFAULT 0 NOT NULL, default_duration INT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `setting` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, field_format VARCHAR(32) NOT NULL, field_available_value LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, field_default_value LONGTEXT DEFAULT NULL, field_required TINYINT(1) DEFAULT NULL, field_value LONGTEXT DEFAULT NULL, special_attributes JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_9F74B898989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sexo (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, code VARCHAR(10) DEFAULT NULL, is_active TINYINT(1) NOT NULL, id_estado INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE specialty (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, category VARCHAR(100) DEFAULT NULL, requires_certification TINYINT(1) DEFAULT 0 NOT NULL, default_consultation_duration INT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE specialty_branch (id INT AUTO_INCREMENT NOT NULL, specialty_id INT NOT NULL, branch_id INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_89FD01D99A353316 (specialty_id), INDEX IDX_89FD01D9DCD6CC49 (branch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sub_company (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(100) DEFAULT NULL, tax_id VARCHAR(50) DEFAULT NULL, description LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE surgery_item (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(200) NOT NULL, description LONGTEXT DEFAULT NULL, category VARCHAR(100) DEFAULT NULL, unit_of_measure VARCHAR(50) DEFAULT NULL, unit_cost NUMERIC(10, 2) DEFAULT NULL, is_sterile TINYINT(1) DEFAULT 0 NOT NULL, is_disposable TINYINT(1) DEFAULT 0 NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `tax_affectation_type` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tenant_module_permission_override (id INT AUTO_INCREMENT NOT NULL, module_name VARCHAR(100) NOT NULL, required_roles JSON NOT NULL, description VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX unique_module_permission (module_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tenant_permission_profile (id INT AUTO_INCREMENT NOT NULL, profile_type VARCHAR(50) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE treatment_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) DEFAULT NULL, name VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, requires_specialist TINYINT(1) DEFAULT 0 NOT NULL, requires_authorization TINYINT(1) DEFAULT 0 NOT NULL, average_duration_days INT DEFAULT NULL, is_active TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE warehouse (id INT AUTO_INCREMENT NOT NULL, service_id INT DEFAULT NULL, parent_warehouse_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, short_name VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, creates_article TINYINT(1) NOT NULL, is_virtual TINYINT(1) NOT NULL, is_pharmacy TINYINT(1) NOT NULL, is_automatic_reception TINYINT(1) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_ECB38BFCED5CA9E6 (service_id), INDEX IDX_ECB38BFCEEB1F0 (parent_warehouse_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE warehouse_medical_service (id INT AUTO_INCREMENT NOT NULL, warehouse_id INT NOT NULL, medical_service_id INT NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E698EAF5080ECDE (warehouse_id), INDEX IDX_E698EAFC61D802A (medical_service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE agreement ADD CONSTRAINT FK_2E655A24C17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id)');
        $this->addSql('ALTER TABLE agreement ADD CONSTRAINT FK_2E655A24E3FB3114 FOREIGN KEY (requesting_company_id) REFERENCES requesting_company (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844A40BC2D5 FOREIGN KEY (schedule_id) REFERENCES schedule (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844DB77003 FOREIGN KEY (professional_id) REFERENCES professional (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844804F7D71 FOREIGN KEY (consultation_type_id) REFERENCES consultation_type (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844C17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8442F8B0EB2 FOREIGN KEY (authorization_id) REFERENCES authorization (id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844B0AFEE5E FOREIGN KEY (cancellation_type_id) REFERENCES cancellation_type (id)');
        $this->addSql('ALTER TABLE authorization ADD CONSTRAINT FK_7A6D8BEFC17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id)');
        $this->addSql('ALTER TABLE authorization ADD CONSTRAINT FK_7A6D8BEFAC8DE0F FOREIGN KEY (service_type_id) REFERENCES service_type (id)');
        $this->addSql('ALTER TABLE bed ADD CONSTRAINT FK_E647FCFF8158330E FOREIGN KEY (bed_type_id) REFERENCES bed_type (id)');
        $this->addSql('ALTER TABLE bed ADD CONSTRAINT FK_E647FCFF54177093 FOREIGN KEY (room_id) REFERENCES room (id)');
        $this->addSql('ALTER TABLE branch_payer ADD CONSTRAINT FK_2F7A59CEDCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id)');
        $this->addSql('ALTER TABLE branch_payer ADD CONSTRAINT FK_2F7A59CEC17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id)');
        $this->addSql('ALTER TABLE branch_service_type ADD CONSTRAINT FK_1F793463DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id)');
        $this->addSql('ALTER TABLE branch_service_type ADD CONSTRAINT FK_1F793463AC8DE0F FOREIGN KEY (service_type_id) REFERENCES service_type (id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18ADCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id)');
        $this->addSql('ALTER TABLE exam_package ADD CONSTRAINT FK_D3CE3EFDC61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id)');
        $this->addSql('ALTER TABLE exam_package_detail ADD CONSTRAINT FK_8E28E519E644D1AA FOREIGN KEY (exam_package_id) REFERENCES exam_package (id)');
        $this->addSql('ALTER TABLE exam_package_detail ADD CONSTRAINT FK_8E28E519C61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id)');
        $this->addSql('ALTER TABLE group_permission ADD CONSTRAINT FK_3784F318FE54D947 FOREIGN KEY (group_id) REFERENCES member_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_permission ADD CONSTRAINT FK_3784F318B03A8386 FOREIGN KEY (created_by_id) REFERENCES `member` (id)');
        $this->addSql('ALTER TABLE `health_insurance` ADD CONSTRAINT FK_558804DE54CCFBDD FOREIGN KEY (health_insurance_type_id) REFERENCES health_insurance_type (id)');
        $this->addSql('ALTER TABLE `health_insurance` ADD CONSTRAINT FK_558804DE588DA015 FOREIGN KEY (tax_affectation_type_id) REFERENCES `tax_affectation_type` (id)');
        $this->addSql('ALTER TABLE maintainer_education_level_detail ADD CONSTRAINT FK_D867A8A7D7A5352E FOREIGN KEY (education_level_id) REFERENCES `education_level` (id)');
        $this->addSql('ALTER TABLE maintainer_origin ADD CONSTRAINT FK_23B5077C703B99FE FOREIGN KEY (origin_type_id) REFERENCES maintainer_origin_type (id)');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1C5C011B5 FOREIGN KEY (figure_id) REFERENCES figure (id)');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1CD0EC18BF FOREIGN KEY (budget_item_id) REFERENCES budget_item (id)');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1CAC8DE0F FOREIGN KEY (service_type_id) REFERENCES service_type (id)');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1CBB50891B FOREIGN KEY (sub_company_id) REFERENCES sub_company (id)');
        $this->addSql('ALTER TABLE medical_service ADD CONSTRAINT FK_A79F7A1C3395B1AC FOREIGN KEY (billing_sub_company_id) REFERENCES sub_company (id)');
        $this->addSql('ALTER TABLE medical_service_bed_type ADD CONSTRAINT FK_EEE3D850C61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id)');
        $this->addSql('ALTER TABLE medical_service_bed_type ADD CONSTRAINT FK_EEE3D8508158330E FOREIGN KEY (bed_type_id) REFERENCES bed_type (id)');
        $this->addSql('ALTER TABLE medical_service_budget_item ADD CONSTRAINT FK_9E9803FBC61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id)');
        $this->addSql('ALTER TABLE medical_service_budget_item ADD CONSTRAINT FK_9E9803FBA4665449 FOREIGN KEY (surgery_item_id) REFERENCES surgery_item (id)');
        $this->addSql('ALTER TABLE medical_service_service ADD CONSTRAINT FK_D8EE37BEC61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id)');
        $this->addSql('ALTER TABLE medical_service_service ADD CONSTRAINT FK_D8EE37BEED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE member_group_membership ADD CONSTRAINT FK_61D5C0D17597D3FE FOREIGN KEY (member_id) REFERENCES `member` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE member_group_membership ADD CONSTRAINT FK_61D5C0D19897AAD FOREIGN KEY (member_group_id) REFERENCES member_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT FK_70B2CA2A727ACA70 FOREIGN KEY (parent_id) REFERENCES menu_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `municipality` ADD CONSTRAINT FK_C6F56628E946114A FOREIGN KEY (province_id) REFERENCES `province` (id)');
        $this->addSql('ALTER TABLE pathology_article ADD CONSTRAINT FK_B24A1BE1541D0E27 FOREIGN KEY (ges_pathology_id) REFERENCES ges_pathology (id)');
        $this->addSql('ALTER TABLE payer ADD CONSTRAINT FK_41CB5B99BEA5E0F7 FOREIGN KEY (payer_type_id) REFERENCES payer_type (id)');
        $this->addSql('ALTER TABLE permission ADD CONSTRAINT FK_E04992AAA76ED395 FOREIGN KEY (user_id) REFERENCES `member` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE permission ADD CONSTRAINT FK_E04992AAB03A8386 FOREIGN KEY (created_by_id) REFERENCES `member` (id)');
        $this->addSql('ALTER TABLE `person` ADD CONSTRAINT FK_34DCD176F54A83F FOREIGN KEY (identification_type_id) REFERENCES `identification_type` (id)');
        $this->addSql('ALTER TABLE `person` ADD CONSTRAINT FK_34DCD176D7A5352E FOREIGN KEY (education_level_id) REFERENCES `education_level` (id)');
        $this->addSql('ALTER TABLE `person` ADD CONSTRAINT FK_34DCD176E559F9BF FOREIGN KEY (marital_status_id) REFERENCES `marital_status` (id)');
        $this->addSql('ALTER TABLE `person` ADD CONSTRAINT FK_34DCD17622C8FC20 FOREIGN KEY (occupation_id) REFERENCES `occupation` (id)');
        $this->addSql('ALTER TABLE `person` ADD CONSTRAINT FK_34DCD176E7EEEDB3 FOREIGN KEY (ethnic_group_id) REFERENCES `ethnic_group` (id)');
        $this->addSql('ALTER TABLE `person` ADD CONSTRAINT FK_34DCD176B7850CBD FOREIGN KEY (religion_id) REFERENCES `religion` (id)');
        $this->addSql('ALTER TABLE `person` ADD CONSTRAINT FK_34DCD176708A0E0 FOREIGN KEY (gender_id) REFERENCES sexo (id)');
        $this->addSql('ALTER TABLE `person` ADD CONSTRAINT FK_34DCD1767949DE26 FOREIGN KEY (nacionality_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08A14E0760 FOREIGN KEY (id_person_id) REFERENCES `person` (id)');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08AE6F181C FOREIGN KEY (municipality_id) REFERENCES `municipality` (id)');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE professional ADD CONSTRAINT FK_B3B573AA9A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id)');
        $this->addSql('ALTER TABLE professional_rate ADD CONSTRAINT FK_CDA906E7DB77003 FOREIGN KEY (professional_id) REFERENCES professional (id)');
        $this->addSql('ALTER TABLE professional_rate ADD CONSTRAINT FK_CDA906E7ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE professional_rate ADD CONSTRAINT FK_CDA906E7C17AD9A9 FOREIGN KEY (payer_id) REFERENCES payer (id)');
        $this->addSql('ALTER TABLE `province` ADD CONSTRAINT FK_4ADAD40B98260155 FOREIGN KEY (region_id) REFERENCES `region` (id)');
        $this->addSql('ALTER TABLE `region` ADD CONSTRAINT FK_F62F176F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES `member` (id)');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519BCC22AD4 FOREIGN KEY (clinic_id) REFERENCES clinic (id)');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FBDB77003 FOREIGN KEY (professional_id) REFERENCES professional (id)');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB804F7D71 FOREIGN KEY (consultation_type_id) REFERENCES consultation_type (id)');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT FK_5A3811FB6DB2886B FOREIGN KEY (blocking_type_id) REFERENCES blocking_type (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD2AC8DE0F FOREIGN KEY (service_type_id) REFERENCES service_type (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD29A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id)');
        $this->addSql('ALTER TABLE service_package_detail ADD CONSTRAINT FK_139B51F9621D924B FOREIGN KEY (service_package_id) REFERENCES service_package (id)');
        $this->addSql('ALTER TABLE service_package_detail ADD CONSTRAINT FK_139B51F9C61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id)');
        $this->addSql('ALTER TABLE specialty_branch ADD CONSTRAINT FK_89FD01D99A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id)');
        $this->addSql('ALTER TABLE specialty_branch ADD CONSTRAINT FK_89FD01D9DCD6CC49 FOREIGN KEY (branch_id) REFERENCES branch (id)');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCEEB1F0 FOREIGN KEY (parent_warehouse_id) REFERENCES warehouse (id)');
        $this->addSql('ALTER TABLE warehouse_medical_service ADD CONSTRAINT FK_E698EAF5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)');
        $this->addSql('ALTER TABLE warehouse_medical_service ADD CONSTRAINT FK_E698EAFC61D802A FOREIGN KEY (medical_service_id) REFERENCES medical_service (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agreement DROP FOREIGN KEY FK_2E655A24C17AD9A9');
        $this->addSql('ALTER TABLE agreement DROP FOREIGN KEY FK_2E655A24E3FB3114');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F844A40BC2D5');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F844DB77003');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F844804F7D71');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F844C17AD9A9');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F8442F8B0EB2');
        $this->addSql('ALTER TABLE appointment DROP FOREIGN KEY FK_FE38F844B0AFEE5E');
        $this->addSql('ALTER TABLE authorization DROP FOREIGN KEY FK_7A6D8BEFC17AD9A9');
        $this->addSql('ALTER TABLE authorization DROP FOREIGN KEY FK_7A6D8BEFAC8DE0F');
        $this->addSql('ALTER TABLE bed DROP FOREIGN KEY FK_E647FCFF8158330E');
        $this->addSql('ALTER TABLE bed DROP FOREIGN KEY FK_E647FCFF54177093');
        $this->addSql('ALTER TABLE branch_payer DROP FOREIGN KEY FK_2F7A59CEDCD6CC49');
        $this->addSql('ALTER TABLE branch_payer DROP FOREIGN KEY FK_2F7A59CEC17AD9A9');
        $this->addSql('ALTER TABLE branch_service_type DROP FOREIGN KEY FK_1F793463DCD6CC49');
        $this->addSql('ALTER TABLE branch_service_type DROP FOREIGN KEY FK_1F793463AC8DE0F');
        $this->addSql('ALTER TABLE department DROP FOREIGN KEY FK_CD1DE18ADCD6CC49');
        $this->addSql('ALTER TABLE exam_package DROP FOREIGN KEY FK_D3CE3EFDC61D802A');
        $this->addSql('ALTER TABLE exam_package_detail DROP FOREIGN KEY FK_8E28E519E644D1AA');
        $this->addSql('ALTER TABLE exam_package_detail DROP FOREIGN KEY FK_8E28E519C61D802A');
        $this->addSql('ALTER TABLE group_permission DROP FOREIGN KEY FK_3784F318FE54D947');
        $this->addSql('ALTER TABLE group_permission DROP FOREIGN KEY FK_3784F318B03A8386');
        $this->addSql('ALTER TABLE `health_insurance` DROP FOREIGN KEY FK_558804DE54CCFBDD');
        $this->addSql('ALTER TABLE `health_insurance` DROP FOREIGN KEY FK_558804DE588DA015');
        $this->addSql('ALTER TABLE maintainer_education_level_detail DROP FOREIGN KEY FK_D867A8A7D7A5352E');
        $this->addSql('ALTER TABLE maintainer_origin DROP FOREIGN KEY FK_23B5077C703B99FE');
        $this->addSql('ALTER TABLE medical_service DROP FOREIGN KEY FK_A79F7A1C5C011B5');
        $this->addSql('ALTER TABLE medical_service DROP FOREIGN KEY FK_A79F7A1CD0EC18BF');
        $this->addSql('ALTER TABLE medical_service DROP FOREIGN KEY FK_A79F7A1CAC8DE0F');
        $this->addSql('ALTER TABLE medical_service DROP FOREIGN KEY FK_A79F7A1CBB50891B');
        $this->addSql('ALTER TABLE medical_service DROP FOREIGN KEY FK_A79F7A1C3395B1AC');
        $this->addSql('ALTER TABLE medical_service_bed_type DROP FOREIGN KEY FK_EEE3D850C61D802A');
        $this->addSql('ALTER TABLE medical_service_bed_type DROP FOREIGN KEY FK_EEE3D8508158330E');
        $this->addSql('ALTER TABLE medical_service_budget_item DROP FOREIGN KEY FK_9E9803FBC61D802A');
        $this->addSql('ALTER TABLE medical_service_budget_item DROP FOREIGN KEY FK_9E9803FBA4665449');
        $this->addSql('ALTER TABLE medical_service_service DROP FOREIGN KEY FK_D8EE37BEC61D802A');
        $this->addSql('ALTER TABLE medical_service_service DROP FOREIGN KEY FK_D8EE37BEED5CA9E6');
        $this->addSql('ALTER TABLE member_group_membership DROP FOREIGN KEY FK_61D5C0D17597D3FE');
        $this->addSql('ALTER TABLE member_group_membership DROP FOREIGN KEY FK_61D5C0D19897AAD');
        $this->addSql('ALTER TABLE menu_items DROP FOREIGN KEY FK_70B2CA2A727ACA70');
        $this->addSql('ALTER TABLE `municipality` DROP FOREIGN KEY FK_C6F56628E946114A');
        $this->addSql('ALTER TABLE pathology_article DROP FOREIGN KEY FK_B24A1BE1541D0E27');
        $this->addSql('ALTER TABLE payer DROP FOREIGN KEY FK_41CB5B99BEA5E0F7');
        $this->addSql('ALTER TABLE permission DROP FOREIGN KEY FK_E04992AAA76ED395');
        $this->addSql('ALTER TABLE permission DROP FOREIGN KEY FK_E04992AAB03A8386');
        $this->addSql('ALTER TABLE `person` DROP FOREIGN KEY FK_34DCD176F54A83F');
        $this->addSql('ALTER TABLE `person` DROP FOREIGN KEY FK_34DCD176D7A5352E');
        $this->addSql('ALTER TABLE `person` DROP FOREIGN KEY FK_34DCD176E559F9BF');
        $this->addSql('ALTER TABLE `person` DROP FOREIGN KEY FK_34DCD17622C8FC20');
        $this->addSql('ALTER TABLE `person` DROP FOREIGN KEY FK_34DCD176E7EEEDB3');
        $this->addSql('ALTER TABLE `person` DROP FOREIGN KEY FK_34DCD176B7850CBD');
        $this->addSql('ALTER TABLE `person` DROP FOREIGN KEY FK_34DCD176708A0E0');
        $this->addSql('ALTER TABLE `person` DROP FOREIGN KEY FK_34DCD1767949DE26');
        $this->addSql('ALTER TABLE person_address DROP FOREIGN KEY FK_2FD0DC08A14E0760');
        $this->addSql('ALTER TABLE person_address DROP FOREIGN KEY FK_2FD0DC08AE6F181C');
        $this->addSql('ALTER TABLE person_address DROP FOREIGN KEY FK_2FD0DC08F92F3E70');
        $this->addSql('ALTER TABLE professional DROP FOREIGN KEY FK_B3B573AA9A353316');
        $this->addSql('ALTER TABLE professional_rate DROP FOREIGN KEY FK_CDA906E7DB77003');
        $this->addSql('ALTER TABLE professional_rate DROP FOREIGN KEY FK_CDA906E7ED5CA9E6');
        $this->addSql('ALTER TABLE professional_rate DROP FOREIGN KEY FK_CDA906E7C17AD9A9');
        $this->addSql('ALTER TABLE `province` DROP FOREIGN KEY FK_4ADAD40B98260155');
        $this->addSql('ALTER TABLE `region` DROP FOREIGN KEY FK_F62F176F92F3E70');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE room DROP FOREIGN KEY FK_729F519BCC22AD4');
        $this->addSql('ALTER TABLE schedule DROP FOREIGN KEY FK_5A3811FBDB77003');
        $this->addSql('ALTER TABLE schedule DROP FOREIGN KEY FK_5A3811FB804F7D71');
        $this->addSql('ALTER TABLE schedule DROP FOREIGN KEY FK_5A3811FB6DB2886B');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD2AC8DE0F');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD29A353316');
        $this->addSql('ALTER TABLE service_package_detail DROP FOREIGN KEY FK_139B51F9621D924B');
        $this->addSql('ALTER TABLE service_package_detail DROP FOREIGN KEY FK_139B51F9C61D802A');
        $this->addSql('ALTER TABLE specialty_branch DROP FOREIGN KEY FK_89FD01D99A353316');
        $this->addSql('ALTER TABLE specialty_branch DROP FOREIGN KEY FK_89FD01D9DCD6CC49');
        $this->addSql('ALTER TABLE warehouse DROP FOREIGN KEY FK_ECB38BFCED5CA9E6');
        $this->addSql('ALTER TABLE warehouse DROP FOREIGN KEY FK_ECB38BFCEEB1F0');
        $this->addSql('ALTER TABLE warehouse_medical_service DROP FOREIGN KEY FK_E698EAF5080ECDE');
        $this->addSql('ALTER TABLE warehouse_medical_service DROP FOREIGN KEY FK_E698EAFC61D802A');
        $this->addSql('DROP TABLE agreement');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE article_package');
        $this->addSql('DROP TABLE authorization');
        $this->addSql('DROP TABLE bed');
        $this->addSql('DROP TABLE bed_type');
        $this->addSql('DROP TABLE blocking_type');
        $this->addSql('DROP TABLE branch');
        $this->addSql('DROP TABLE branch_payer');
        $this->addSql('DROP TABLE branch_service_type');
        $this->addSql('DROP TABLE budget_item');
        $this->addSql('DROP TABLE `business_activity`');
        $this->addSql('DROP TABLE cancellation_type');
        $this->addSql('DROP TABLE clinic');
        $this->addSql('DROP TABLE consultation_type');
        $this->addSql('DROP TABLE cost_center');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE `education_level`');
        $this->addSql('DROP TABLE eno_pathology');
        $this->addSql('DROP TABLE `ethnic_group`');
        $this->addSql('DROP TABLE exam_package');
        $this->addSql('DROP TABLE exam_package_detail');
        $this->addSql('DROP TABLE external_referrer');
        $this->addSql('DROP TABLE figure');
        $this->addSql('DROP TABLE ges_pathology');
        $this->addSql('DROP TABLE group_permission');
        $this->addSql('DROP TABLE `health_insurance`');
        $this->addSql('DROP TABLE health_insurance_type');
        $this->addSql('DROP TABLE `identification_type`');
        $this->addSql('DROP TABLE maintainer_doctor_type');
        $this->addSql('DROP TABLE maintainer_education_level_detail');
        $this->addSql('DROP TABLE maintainer_insurance_administrator');
        $this->addSql('DROP TABLE maintainer_job_position');
        $this->addSql('DROP TABLE maintainer_location');
        $this->addSql('DROP TABLE maintainer_medical_box');
        $this->addSql('DROP TABLE maintainer_origin');
        $this->addSql('DROP TABLE maintainer_origin_type');
        $this->addSql('DROP TABLE `marital_status`');
        $this->addSql('DROP TABLE medical_service');
        $this->addSql('DROP TABLE medical_service_bed_type');
        $this->addSql('DROP TABLE medical_service_budget_item');
        $this->addSql('DROP TABLE medical_service_service');
        $this->addSql('DROP TABLE `member`');
        $this->addSql('DROP TABLE member_group_membership');
        $this->addSql('DROP TABLE member_group');
        $this->addSql('DROP TABLE menu_items');
        $this->addSql('DROP TABLE `municipality`');
        $this->addSql('DROP TABLE `occupation`');
        $this->addSql('DROP TABLE pathology_article');
        $this->addSql('DROP TABLE payer');
        $this->addSql('DROP TABLE payer_type');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE `person`');
        $this->addSql('DROP TABLE person_address');
        $this->addSql('DROP TABLE professional');
        $this->addSql('DROP TABLE professional_rate');
        $this->addSql('DROP TABLE `province`');
        $this->addSql('DROP TABLE `region`');
        $this->addSql('DROP TABLE `religion`');
        $this->addSql('DROP TABLE requesting_company');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE schedule');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_package');
        $this->addSql('DROP TABLE service_package_detail');
        $this->addSql('DROP TABLE service_type');
        $this->addSql('DROP TABLE `setting`');
        $this->addSql('DROP TABLE sexo');
        $this->addSql('DROP TABLE specialty');
        $this->addSql('DROP TABLE specialty_branch');
        $this->addSql('DROP TABLE sub_company');
        $this->addSql('DROP TABLE surgery_item');
        $this->addSql('DROP TABLE `tax_affectation_type`');
        $this->addSql('DROP TABLE tenant_module_permission_override');
        $this->addSql('DROP TABLE tenant_permission_profile');
        $this->addSql('DROP TABLE treatment_type');
        $this->addSql('DROP TABLE warehouse');
        $this->addSql('DROP TABLE warehouse_medical_service');
    }
}
