<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260131174355 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE IF EXISTS _schema_subscriber_check_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE "business_activity_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "education_level_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "ethnic_group_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE group_permission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "health_insurance_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE health_insurance_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "identification_type_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_doctor_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_education_level_detail_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_insurance_administrator_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_job_position_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_medical_box_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_origin_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE maintainer_origin_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "marital_status_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE member_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE member_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE menu_items_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "municipality_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "occupation_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pais_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE permission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "person_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE person_address_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "province_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "region_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "religion_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reset_password_request_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sexo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE "tax_affectation_type_id_seq" INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tenant_module_permission_override_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tenant_permission_profile_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE "business_activity" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "education_level" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "ethnic_group" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE group_permission (id INT NOT NULL, group_id INT NOT NULL, created_by_id INT DEFAULT NULL, domain VARCHAR(100) NOT NULL, resource_id INT DEFAULT NULL, field_name VARCHAR(100) DEFAULT NULL, can_view BOOLEAN NOT NULL, can_edit BOOLEAN NOT NULL, can_delete BOOLEAN NOT NULL, constraints JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3784F318FE54D947 ON group_permission (group_id)');
        $this->addSql('CREATE INDEX IDX_3784F318B03A8386 ON group_permission (created_by_id)');
        $this->addSql('CREATE INDEX idx_group_permission_domain ON group_permission (domain)');
        $this->addSql('CREATE INDEX idx_group_permission_resource ON group_permission (domain, resource_id)');
        $this->addSql('COMMENT ON COLUMN group_permission.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "health_insurance" (id INT NOT NULL, health_insurance_type_id INT DEFAULT NULL, tax_affectation_type_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, interface_code VARCHAR(100) DEFAULT NULL, id_imed INT DEFAULT NULL, abbreviated_name VARCHAR(45) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, healthcare_prevition_hl7 VARCHAR(30) DEFAULT NULL, icon VARCHAR(45) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_558804DE54CCFBDD ON "health_insurance" (health_insurance_type_id)');
        $this->addSql('CREATE INDEX IDX_558804DE588DA015 ON "health_insurance" (tax_affectation_type_id)');
        $this->addSql('CREATE TABLE health_insurance_type (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, is_agreement BOOLEAN DEFAULT true NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "identification_type" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_doctor_type (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_education_level_detail (id INT NOT NULL, education_level_id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D867A8A7D7A5352E ON maintainer_education_level_detail (education_level_id)');
        $this->addSql('CREATE TABLE maintainer_insurance_administrator (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, rut VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_job_position (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_location (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, building VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_medical_box (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, capacity INT DEFAULT NULL, floor VARCHAR(50) DEFAULT NULL, building VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE maintainer_origin (id INT NOT NULL, origin_type_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_23B5077C703B99FE ON maintainer_origin (origin_type_id)');
        $this->addSql('CREATE TABLE maintainer_origin_type (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) DEFAULT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "marital_status" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, marital_status_code_hl7 VARCHAR(2) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE member (id INT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON member (username)');
        $this->addSql('COMMENT ON COLUMN member.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN member.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE member_group_membership (member_id INT NOT NULL, member_group_id INT NOT NULL, PRIMARY KEY(member_id, member_group_id))');
        $this->addSql('CREATE INDEX IDX_61D5C0D17597D3FE ON member_group_membership (member_id)');
        $this->addSql('CREATE INDEX IDX_61D5C0D19897AAD ON member_group_membership (member_group_id)');
        $this->addSql('CREATE TABLE member_group (id INT NOT NULL, name VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, description VARCHAR(500) DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE1D13677153098 ON member_group (code)');
        $this->addSql('COMMENT ON COLUMN member_group.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN member_group.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE menu_items (id INT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, route VARCHAR(255) DEFAULT NULL, icon VARCHAR(100) DEFAULT NULL, module VARCHAR(100) DEFAULT NULL, position INT NOT NULL, enabled BOOLEAN NOT NULL, visible_in_sidebar BOOLEAN NOT NULL, requires_auth BOOLEAN NOT NULL, required_roles JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_70B2CA2A727ACA70 ON menu_items (parent_id)');
        $this->addSql('CREATE TABLE "municipality" (id INT NOT NULL, province_id INT NOT NULL, name VARCHAR(100) NOT NULL, municipality_code_hl7 VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C6F56628E946114A ON "municipality" (province_id)');
        $this->addSql('CREATE TABLE "occupation" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pais (id INT NOT NULL, nombre_pais VARCHAR(255) DEFAULT NULL, nombre_gentilicio VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, id_estado BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE permission (id INT NOT NULL, user_id INT NOT NULL, created_by_id INT DEFAULT NULL, domain VARCHAR(100) NOT NULL, resource_id INT DEFAULT NULL, field_name VARCHAR(100) DEFAULT NULL, can_view BOOLEAN NOT NULL, can_edit BOOLEAN NOT NULL, can_delete BOOLEAN NOT NULL, constraints JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E04992AAA76ED395 ON permission (user_id)');
        $this->addSql('CREATE INDEX IDX_E04992AAB03A8386 ON permission (created_by_id)');
        $this->addSql('CREATE INDEX IDX_E04992AAA76ED395A7A91E0B ON permission (user_id, domain)');
        $this->addSql('CREATE INDEX IDX_E04992AAA7A91E0B89329D25 ON permission (domain, resource_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_permission ON permission (user_id, domain, resource_id, field_name)');
        $this->addSql('COMMENT ON COLUMN permission.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "person" (id INT NOT NULL, identification_type_id INT DEFAULT NULL, education_level_id INT DEFAULT NULL, marital_status_id INT DEFAULT NULL, occupation_id INT DEFAULT NULL, ethnic_group_id INT DEFAULT NULL, religion_id INT DEFAULT NULL, gender_id INT DEFAULT NULL, nacionality_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, identification VARCHAR(100) NOT NULL, name VARCHAR(60) NOT NULL, last_name VARCHAR(45) NOT NULL, middle_name VARCHAR(45) DEFAULT NULL, birth_date_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, death_date_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, non_medical_note TEXT DEFAULT NULL, photo_path VARCHAR(255) DEFAULT NULL, is_record_visibility BOOLEAN DEFAULT true NOT NULL, record_viewed_date_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, social_name VARCHAR(50) DEFAULT NULL, number_of_children INT DEFAULT NULL, mobile_phone VARCHAR(20) NOT NULL, work_phone VARCHAR(20) DEFAULT NULL, home_phone VARCHAR(20) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, secondary_email VARCHAR(100) DEFAULT NULL, contact_method VARCHAR(50) DEFAULT NULL, twin_number INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_34DCD176F54A83F ON "person" (identification_type_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176D7A5352E ON "person" (education_level_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176E559F9BF ON "person" (marital_status_id)');
        $this->addSql('CREATE INDEX IDX_34DCD17622C8FC20 ON "person" (occupation_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176E7EEEDB3 ON "person" (ethnic_group_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176B7850CBD ON "person" (religion_id)');
        $this->addSql('CREATE INDEX IDX_34DCD176708A0E0 ON "person" (gender_id)');
        $this->addSql('CREATE INDEX IDX_34DCD1767949DE26 ON "person" (nacionality_id)');
        $this->addSql('COMMENT ON COLUMN "person".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "person".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "person".birth_date_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "person".death_date_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "person".record_viewed_date_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE person_address (id INT NOT NULL, id_person_id INT DEFAULT NULL, municipality_id INT DEFAULT NULL, country_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, address VARCHAR(255) NOT NULL, street_number VARCHAR(10) NOT NULL, address_details VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FD0DC08A14E0760 ON person_address (id_person_id)');
        $this->addSql('CREATE INDEX IDX_2FD0DC08AE6F181C ON person_address (municipality_id)');
        $this->addSql('CREATE INDEX IDX_2FD0DC08F92F3E70 ON person_address (country_id)');
        $this->addSql('COMMENT ON COLUMN person_address.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "province" (id INT NOT NULL, region_id INT NOT NULL, name VARCHAR(100) NOT NULL, province_code_hl7 VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4ADAD40B98260155 ON "province" (region_id)');
        $this->addSql('CREATE TABLE "region" (id INT NOT NULL, country_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, address_state_hl7 VARCHAR(10) DEFAULT NULL, region_code_hl7 VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F62F176F92F3E70 ON "region" (country_id)');
        $this->addSql('CREATE TABLE "religion" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_default_value BOOLEAN DEFAULT true NOT NULL, religion_code_hl7 VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE reset_password_request (id INT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('COMMENT ON COLUMN reset_password_request.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "setting" (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, field_format VARCHAR(32) NOT NULL, field_available_value TEXT DEFAULT NULL, description TEXT DEFAULT NULL, field_default_value TEXT DEFAULT NULL, field_required BOOLEAN DEFAULT NULL, field_value TEXT DEFAULT NULL, special_attributes JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F74B898989D9B62 ON "setting" (slug)');
        $this->addSql('COMMENT ON COLUMN "setting".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "setting".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE sexo (id INT NOT NULL, name VARCHAR(50) NOT NULL, code VARCHAR(10) DEFAULT NULL, is_active BOOLEAN NOT NULL, id_estado INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "tax_affectation_type" (id INT NOT NULL, name VARCHAR(100) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tenant_module_permission_override (id INT NOT NULL, module_name VARCHAR(100) NOT NULL, required_roles JSON NOT NULL, description VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX unique_module_permission ON tenant_module_permission_override (module_name)');
        $this->addSql('COMMENT ON COLUMN tenant_module_permission_override.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tenant_module_permission_override.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE tenant_permission_profile (id INT NOT NULL, profile_type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN tenant_permission_profile.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN tenant_permission_profile.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE group_permission ADD CONSTRAINT FK_3784F318FE54D947 FOREIGN KEY (group_id) REFERENCES member_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_permission ADD CONSTRAINT FK_3784F318B03A8386 FOREIGN KEY (created_by_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "health_insurance" ADD CONSTRAINT FK_558804DE54CCFBDD FOREIGN KEY (health_insurance_type_id) REFERENCES health_insurance_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "health_insurance" ADD CONSTRAINT FK_558804DE588DA015 FOREIGN KEY (tax_affectation_type_id) REFERENCES "tax_affectation_type" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maintainer_education_level_detail ADD CONSTRAINT FK_D867A8A7D7A5352E FOREIGN KEY (education_level_id) REFERENCES "education_level" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE maintainer_origin ADD CONSTRAINT FK_23B5077C703B99FE FOREIGN KEY (origin_type_id) REFERENCES maintainer_origin_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE member_group_membership ADD CONSTRAINT FK_61D5C0D17597D3FE FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE member_group_membership ADD CONSTRAINT FK_61D5C0D19897AAD FOREIGN KEY (member_group_id) REFERENCES member_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu_items ADD CONSTRAINT FK_70B2CA2A727ACA70 FOREIGN KEY (parent_id) REFERENCES menu_items (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "municipality" ADD CONSTRAINT FK_C6F56628E946114A FOREIGN KEY (province_id) REFERENCES "province" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permission ADD CONSTRAINT FK_E04992AAA76ED395 FOREIGN KEY (user_id) REFERENCES member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE permission ADD CONSTRAINT FK_E04992AAB03A8386 FOREIGN KEY (created_by_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176F54A83F FOREIGN KEY (identification_type_id) REFERENCES "identification_type" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176D7A5352E FOREIGN KEY (education_level_id) REFERENCES "education_level" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176E559F9BF FOREIGN KEY (marital_status_id) REFERENCES "marital_status" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD17622C8FC20 FOREIGN KEY (occupation_id) REFERENCES "occupation" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176E7EEEDB3 FOREIGN KEY (ethnic_group_id) REFERENCES "ethnic_group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176B7850CBD FOREIGN KEY (religion_id) REFERENCES "religion" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD176708A0E0 FOREIGN KEY (gender_id) REFERENCES sexo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "person" ADD CONSTRAINT FK_34DCD1767949DE26 FOREIGN KEY (nacionality_id) REFERENCES pais (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08A14E0760 FOREIGN KEY (id_person_id) REFERENCES "person" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08AE6F181C FOREIGN KEY (municipality_id) REFERENCES "municipality" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_address ADD CONSTRAINT FK_2FD0DC08F92F3E70 FOREIGN KEY (country_id) REFERENCES pais (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "province" ADD CONSTRAINT FK_4ADAD40B98260155 FOREIGN KEY (region_id) REFERENCES "region" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "region" ADD CONSTRAINT FK_F62F176F92F3E70 FOREIGN KEY (country_id) REFERENCES pais (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE IF EXISTS _schema_subscriber_check');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE "business_activity_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE "education_level_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE "ethnic_group_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE group_permission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "health_insurance_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE health_insurance_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "identification_type_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_doctor_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_education_level_detail_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_insurance_administrator_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_job_position_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_medical_box_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_origin_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE maintainer_origin_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "marital_status_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE member_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE member_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE menu_items_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "municipality_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE "occupation_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE pais_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE permission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "person_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE person_address_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "province_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE "region_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE "religion_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE reset_password_request_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sexo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE "tax_affectation_type_id_seq" CASCADE');
        $this->addSql('DROP SEQUENCE tenant_module_permission_override_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tenant_permission_profile_id_seq CASCADE');
        $this->addSql('CREATE SEQUENCE _schema_subscriber_check_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE _schema_subscriber_check (id SERIAL NOT NULL, random_key VARCHAR(14) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE group_permission DROP CONSTRAINT FK_3784F318FE54D947');
        $this->addSql('ALTER TABLE group_permission DROP CONSTRAINT FK_3784F318B03A8386');
        $this->addSql('ALTER TABLE "health_insurance" DROP CONSTRAINT FK_558804DE54CCFBDD');
        $this->addSql('ALTER TABLE "health_insurance" DROP CONSTRAINT FK_558804DE588DA015');
        $this->addSql('ALTER TABLE maintainer_education_level_detail DROP CONSTRAINT FK_D867A8A7D7A5352E');
        $this->addSql('ALTER TABLE maintainer_origin DROP CONSTRAINT FK_23B5077C703B99FE');
        $this->addSql('ALTER TABLE member_group_membership DROP CONSTRAINT FK_61D5C0D17597D3FE');
        $this->addSql('ALTER TABLE member_group_membership DROP CONSTRAINT FK_61D5C0D19897AAD');
        $this->addSql('ALTER TABLE menu_items DROP CONSTRAINT FK_70B2CA2A727ACA70');
        $this->addSql('ALTER TABLE "municipality" DROP CONSTRAINT FK_C6F56628E946114A');
        $this->addSql('ALTER TABLE permission DROP CONSTRAINT FK_E04992AAA76ED395');
        $this->addSql('ALTER TABLE permission DROP CONSTRAINT FK_E04992AAB03A8386');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176F54A83F');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176D7A5352E');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176E559F9BF');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD17622C8FC20');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176E7EEEDB3');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176B7850CBD');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD176708A0E0');
        $this->addSql('ALTER TABLE "person" DROP CONSTRAINT FK_34DCD1767949DE26');
        $this->addSql('ALTER TABLE person_address DROP CONSTRAINT FK_2FD0DC08A14E0760');
        $this->addSql('ALTER TABLE person_address DROP CONSTRAINT FK_2FD0DC08AE6F181C');
        $this->addSql('ALTER TABLE person_address DROP CONSTRAINT FK_2FD0DC08F92F3E70');
        $this->addSql('ALTER TABLE "province" DROP CONSTRAINT FK_4ADAD40B98260155');
        $this->addSql('ALTER TABLE "region" DROP CONSTRAINT FK_F62F176F92F3E70');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('DROP TABLE "business_activity"');
        $this->addSql('DROP TABLE "education_level"');
        $this->addSql('DROP TABLE "ethnic_group"');
        $this->addSql('DROP TABLE group_permission');
        $this->addSql('DROP TABLE "health_insurance"');
        $this->addSql('DROP TABLE health_insurance_type');
        $this->addSql('DROP TABLE "identification_type"');
        $this->addSql('DROP TABLE maintainer_doctor_type');
        $this->addSql('DROP TABLE maintainer_education_level_detail');
        $this->addSql('DROP TABLE maintainer_insurance_administrator');
        $this->addSql('DROP TABLE maintainer_job_position');
        $this->addSql('DROP TABLE maintainer_location');
        $this->addSql('DROP TABLE maintainer_medical_box');
        $this->addSql('DROP TABLE maintainer_origin');
        $this->addSql('DROP TABLE maintainer_origin_type');
        $this->addSql('DROP TABLE "marital_status"');
        $this->addSql('DROP TABLE member');
        $this->addSql('DROP TABLE member_group_membership');
        $this->addSql('DROP TABLE member_group');
        $this->addSql('DROP TABLE menu_items');
        $this->addSql('DROP TABLE "municipality"');
        $this->addSql('DROP TABLE "occupation"');
        $this->addSql('DROP TABLE pais');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE "person"');
        $this->addSql('DROP TABLE person_address');
        $this->addSql('DROP TABLE "province"');
        $this->addSql('DROP TABLE "region"');
        $this->addSql('DROP TABLE "religion"');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE "setting"');
        $this->addSql('DROP TABLE sexo');
        $this->addSql('DROP TABLE "tax_affectation_type"');
        $this->addSql('DROP TABLE tenant_module_permission_override');
        $this->addSql('DROP TABLE tenant_permission_profile');
    }
}
